#!/bin/sh

updatesarch="$(checkupdates | wc -l)"
updatesaur="$(yay -Qum 2> /dev/null | wc -l)"
#updates=$(("$updatesarch" + "$updatesaur"))
icon1=" "
icon2="ᵃᵘʳ"
printf " %s %s | %s %s \\n"  "$icon1" "$updatesarch" "$icon2" "$updatesaur"
